ignore thing we can't change

diff --git a/rds-clone-parameter-group b/rds-clone-parameter-group
--- a/rds-clone-parameter-group
+++ b/rds-clone-parameter-group
@@ -49,15 +49,17 @@ for item in $DIFFOUTPUT
 do
 	key=`echo $item | cut -d, -f1`
 	value=`echo $item | cut -d, -f2`
-	PARAMETERS="--parameters \"name=$key, value=$value, method=immediate\""
+    if [ "$key" != "core-file" ]
+	    PARAMETERS="--parameters \"name=$key, value=$value, method=immediate\""
 
-    echo "Applying parameters to newly created group ($2)"
-    MODIFY_OUTPUT=`rds-modify-db-parameter-group $2 $PARAMETERS`
+        echo "Applying parameter to newly created group ($2)"
+        MODIFY_OUTPUT=`rds-modify-db-parameter-group $2 $PARAMETERS`
     
-    if [ "$?" -ne "0" ]; then
-    	echo "Error occurred while modifying new group parameters."
-    	echo "$MODIFY_OUTPUT"
-    	exit 1
+        if [ "$?" -ne "0" ]; then
+        	echo "Error occurred while modifying new group parameters."
+        	echo "$MODIFY_OUTPUT"
+        	exit 1
+        fi
     fi
 done
 
