do each one individually so as not to have 20

diff --git a/rds-clone-parameter-group b/rds-clone-parameter-group
--- a/rds-clone-parameter-group
+++ b/rds-clone-parameter-group
@@ -44,24 +44,23 @@ DEST_PARAMS=`rds-describe-db-parameters $2 2>/dev/null`
 # Compare the files, any differences get the source group's value and place into DIFFOUTPUT
 DIFFOUTPUT=`diff <(echo "$SOURCE_PARAMS") <(echo "$DEST_PARAMS") | egrep '^<' | awk '{print \$3","\$4;}'`
 
-PARAMETERS=""
-
 # Loop through DIFFOUTPUT and create a parameter string to use with rds-modify-db-parameter-group
 for item in $DIFFOUTPUT
 do
 	key=`echo $item | cut -d, -f1`
 	value=`echo $item | cut -d, -f2`
-	PARAMETERS="$PARAMETERS --parameters \"name=$key, value=$value, method=immediate\""
+	PARAMETERS="--parameters \"name=$key, value=$value, method=immediate\""
+
+    echo "Applying parameters to newly created group ($2)"
+    MODIFY_OUTPUT=`rds-modify-db-parameter-group $2 $PARAMETERS`
+    
+    if [ "$?" -ne "0" ]; then
+    	echo "Error occurred while modifying new group parameters."
+    	echo "$MODIFY_OUTPUT"
+    	exit 1
+    fi
 done
 
-echo "Applying parameters to newly created group ($2)"
-MODIFY_OUTPUT=`rds-modify-db-parameter-group $2 $PARAMETERS`
-
-if [ "$?" -ne "0" ]; then
-	echo "Error occurred while modifying new group parameters."
-	echo "$MODIFY_OUTPUT"
-	exit 1
-fi
 
 echo "New group created ($2)"
 unset AWS_CREDENTIAL_FILE
